#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  ninestars-frontend
        bind *:80
        mode http
        default_backend cobby-backend
backend cninestars-backend
        balance roundrobin
        server 434802-web-01 54.90.46.196 check
        server 434802-web-02 35.174.211.72 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
