#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

file_content="/etc/passwd"
while IFS= read -r entry
do
   echo "$entry" | cut -d":" -f1,3,6
done < "$file_content"
