#!/usr/bin/env bash
# This is a script that displays 1 to 20 and few words after the 4th, 9th and 17th number

i=1

while [ $i -le 20 ]
do
   echo "$i"
   case $i in
      4)
         echo "bad luck from China"
         ;;
      9)
         echo "bad luck from Japan"
         ;;
      17)
         echo "bad luck from Italy"
         ;;
      *)
         ;;
   esac

   ((i++))
done
