#!/usr/bin/env bash
# This is script that displays the time for 12hrs and 59 minutes

hour=0

while [ $hour -le 12 ]
do
   echo "Hour: $hour"
   min=1
   while [ $min -le 59 ]
   do
      echo "$min"
      ((min++))
   done
   ((hour++))
done
